language: java
jdk:
  - oraclejdk8

sudo: true

services:
  - docker

before_install:
  - docker run -d -p 5672:5672 --name rabbit rabbitmq:alpine

# keep gradle cache
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew clean build test integration coverage

after_script:
  - docker stop rabbit

after_success:
  - bash <(curl -s https://codecov.io/bash)
